Repository codestates/Bobpago, pull requests merged in 2021-11, with the labels that each got.

#175 merge
  README.md
  client/public/img/GifMypage.gif
  client/src/components/Landing/LandSection2.tsx
Labels: 0.5h

#176 [fix] 이메일 인증 버그, bcrypt 적용
  client/src/pages/SignUpAndSignIn/SignUp.tsx
  server/package-lock.json
  server/package.json
  server/src/auth/auth.service.ts
  server/src/auth/dto/request-dto/check-signin.req.dto.ts
  server/src/main.ts
  server/src/me/dto/request-dto/checkInfo-user.req.dto.ts
  server/src/me/dto/request-dto/create-user.req.dto.ts
  server/src/me/dto/request-dto/update-user.req.dto.ts
  server/src/me/me.service.ts
Labels: 1h

#178 Fix/email authentication
  client/src/pages/SignUpAndSignIn/SignUp.tsx
  server/package-lock.json
  server/package.json
  server/src/auth/auth.service.ts
  server/src/auth/dto/request-dto/check-signin.req.dto.ts
  server/src/main.ts
  server/src/me/dto/request-dto/checkInfo-user.req.dto.ts
  server/src/me/dto/request-dto/create-user.req.dto.ts
  server/src/me/dto/request-dto/update-user.req.dto.ts
  server/src/me/me.service.ts
Labels: 1h

#179 [fix] checkMyInfo 비밀번호 확인 에러
  client/src/pages/MyOrUserPage/MyPage.tsx
  server/src/me/me.service.ts
Labels: bug, 1h, complete

#181 11.14 Bobpago refactoring
  server/.gitignore
  server/dist/auth/auth.controller.js
  server/dist/auth/auth.controller.js.map
  server/dist/auth/auth.service.js
  server/dist/auth/auth.service.js.map
  server/dist/auth/dto/request-dto/check-signin.req.dto.d.ts
  server/dist/auth/dto/request-dto/check-signin.req.dto.js
  server/dist/auth/dto/request-dto/check-signin.req.dto.js.map
  server/dist/comments/comments.controller.js.map
  server/dist/entities/user.entity.js
  server/dist/entities/user.entity.js.map
  server/dist/main.js
  server/dist/main.js.map
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.d.ts
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.js
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.js.map
  server/dist/me/dto/request-dto/create-user.req.dto.d.ts
  server/dist/me/dto/request-dto/create-user.req.dto.js
  server/dist/me/dto/request-dto/create-user.req.dto.js.map
  server/dist/me/dto/request-dto/update-user.req.dto.d.ts
  server/dist/me/dto/request-dto/update-user.req.dto.js
  server/dist/me/dto/request-dto/update-user.req.dto.js.map
  server/dist/me/me.controller.js
  server/dist/me/me.controller.js.map
  server/dist/me/me.service.js
  server/dist/me/me.service.js.map
  server/dist/recipes/recipes.service.js
  server/dist/recipes/recipes.service.js.map
  server/dist/tsconfig.build.tsbuildinfo
  server/dist/users/users.controller.js
  server/dist/users/users.controller.js.map
  server/dist/users/users.service.js
  server/dist/users/users.service.js.map
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/comments/comments.controller.ts
  server/src/entities/user.entity.ts
  server/src/me/me.controller.ts
  server/src/me/me.service.ts
  server/src/recipes/recipes.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: server, 1h

#183 [fix] update myInfo
  client/src/pages/MyOrUserPage/MyPage.tsx
  server/dist/me/dto/request-dto/update-user.req.dto.d.ts
  server/dist/me/dto/request-dto/update-user.req.dto.js
  server/dist/me/dto/request-dto/update-user.req.dto.js.map
  server/dist/me/me.service.js
  server/dist/me/me.service.js.map
  server/dist/tsconfig.build.tsbuildinfo
  server/src/me/dto/request-dto/update-user.req.dto.ts
  server/src/me/me.service.ts
Labels: client, server, 2h

#186 merge dev into master
  client/src/pages/MyOrUserPage/MyPage.tsx
  server/.gitignore
  server/dist/auth/auth.controller.js
  server/dist/auth/auth.controller.js.map
  server/dist/auth/auth.service.js
  server/dist/auth/auth.service.js.map
  server/dist/auth/dto/request-dto/check-signin.req.dto.d.ts
  server/dist/auth/dto/request-dto/check-signin.req.dto.js
  server/dist/auth/dto/request-dto/check-signin.req.dto.js.map
  server/dist/comments/comments.controller.js.map
  server/dist/entities/user.entity.js
  server/dist/entities/user.entity.js.map
  server/dist/main.js
  server/dist/main.js.map
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.d.ts
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.js
  server/dist/me/dto/request-dto/checkInfo-user.req.dto.js.map
  server/dist/me/dto/request-dto/create-user.req.dto.d.ts
  server/dist/me/dto/request-dto/create-user.req.dto.js
  server/dist/me/dto/request-dto/create-user.req.dto.js.map
  server/dist/me/dto/request-dto/update-user.req.dto.d.ts
  server/dist/me/dto/request-dto/update-user.req.dto.js
  server/dist/me/dto/request-dto/update-user.req.dto.js.map
  server/dist/me/me.controller.js
  server/dist/me/me.controller.js.map
  server/dist/me/me.service.js
  server/dist/me/me.service.js.map
  server/dist/recipes/recipes.service.js
  server/dist/recipes/recipes.service.js.map
  server/dist/tsconfig.build.tsbuildinfo
  server/dist/users/users.controller.js
  server/dist/users/users.controller.js.map
  server/dist/users/users.service.js
  server/dist/users/users.service.js.map
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/comments/comments.controller.ts
  server/src/entities/user.entity.ts
  server/src/me/dto/request-dto/update-user.req.dto.ts
  server/src/me/me.controller.ts
  server/src/me/me.service.ts
  server/src/recipes/recipes.service.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: complete
